### ISSUE TITLE
Request for Leaflet.timeline!

### ISSUE THREAD

**Issue by dave2004NMC** [rstudio/leaflet#226] opened 2016-01-06 02:52 UTC
Hi, guys. I want to use the timeline function. So can your import the Leaflet.timeline to  leaflet R. Very thanks.

**Comment by mikebirdgeneau** [comment] 2016-02-28 17:19
There are several different plugin implementations to handle time series data in leaflet:
http://leafletjs.com/plugins.html#time--elevation

Is `Leaflet.timeline` the best option, or should we be considering something like `Leaflet.TimeDimension` ([Leaflet.TimeDimension](https://github.com/socib/Leaflet.TimeDimension)) instead. Either way, this function would be very useful for applications I'm working on. 

I'd take a stab at this, but I'm not good with JS, and have no exposure to `htmlwidgets` yet, so it might be a bit of a learning curve.

**Comment by jebyrnes** [comment] 2016-04-06 14:09
Timeline looks simpler for implementation - and broad in what it can do. Does TimeDimension really just focus on rasters? Either one would be amazing, as they really tap into the power of spatiotemporal data.

**Comment by bhaskarvk** [comment] 2017-02-03 19:36
Duplicate of #158

**Closed by bhaskarvk** 2017-02-03 19:36 UTC
