### ISSUE TITLE
FR: adding support for leaflet heat maps

### ISSUE THREAD

**Issue by smartinsightsfromdata** [rstudio/leaflet#28] opened 2015-01-08 15:40 UTC
Vladimir Agafonkin produced this interesting leaflet plugin visible in http://leaflet.github.io/Leaflet.heat/demo/

The actual plug in is available here: https://github.com/Leaflet/Leaflet.heat

Is there a chance to see it added to the RStudio library?

Using some reference on the web I recently hacked a demo of it using rCharts & shiny, but it stopped to work on a recent version of shiny (issue documented here https://github.com/rstudio/shiny/issues/642)

**Comment by bhaskarvk** [comment] 2016-10-11 12:54
Dupe of #233 

Added heatmap support in https://github.com/bhaskarvk/leaflet.extras which will soon be on CRAN.
Demo http://rpubs.com/bhaskarvk/leaflet-heatmap

**Closed by bhaskarvk** 2016-10-11 12:54 UTC
Labels: duplicate, enhancement
