### ISSUE TITLE
feature request: custom CRS support

### ISSUE THREAD

**Issue by peter00k** [rstudio/leaflet#233] opened 2016-02-01 13:28 UTC
Hi, 

Leaflet supports only few projection out of the box. These projections (like WGS84) are mainly suitable to show a map of the entire world. A lot of use cases only require to show a map of a certain area (e.g. country, state, etc.). Depending on the latitude the standard projections can create maps that are very malformed (instead of what maps.google.com [suggests](https://www.google.nl/maps/@57.2632641,-123.949721,3.24z) Alaska [does not](https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Map_of_USA_AK.svg/265px-Map_of_USA_AK.svg.png) represent ~30-35% of United States landmass). 

There is a JS library called [Proj4leaflet](http://kartena.github.io/Proj4Leaflet/) that extends on leaflet and adds supports for all major projections. It would be nice to have these available in leaflet for R. Proj4leaflet provides a branch for leaflet 0.7.x and for the 1.0 branch of leaflet (now in beta 2). Maybe a future switch to the 1.0 branch of leaflet ([issue 175](https://github.com/rstudio/leaflet/issues/175)) could provide an opportunity to also support all major projections through proj4leaflet.

Unfortunately my JS skills are close to non-existent (which is the reason why i'm so happy with rstudio's shiny!) so i don't really know how to contribute myself. What are the plans on switching to leaflet 1.0? Are you waiting for a stable release of leaflet 1.0? 

Peter

**Comment by jcheng5** [comment] 2016-02-01 14:14
That would be really nice.

I haven't moved to 1.0 because of lack of time. First step would be to make sure all the plugins we support have moved to 1.0 too.

**Comment by bhaskarvk** [comment] 2016-02-01 15:06
Proj4js is on my radar of plugins to incorporate. Hoping to find some free time.

**Comment by maarten-vermeyen** [comment] 2016-03-11 19:25
I'm also interested in this feature. I find reprojecting large datasets to be rather expensive and prefer to work with geographical data in it's native CRS. Reprojecting can also result in topological errors if the data wasn't created with topology in mind.

Are there developer guidelines for working on leaflet?

**Comment by jhollist** [comment] 2016-04-07 19:02
:+1:

**Comment by maarten-vermeyen** [comment] 2016-04-12 19:08
This issue seems like a duplicate of / related to #24.

**Comment by gisma** [comment] 2016-04-12 22:19
I absolutely appreciate the integration of proj4leaflet in leaflet for R. Up to this point the functions  projView and makeTile from the [develop](https://github.com/environmentalinformatics-marburg/mapview/tree/develop) branch of the [mapview](https://cran.r-project.org/web/packages/mapview/index.html) package might be useful. 

You will find some explanations at the projView [vignette](http://gisma.github.io/projView/projView1_0_9.html) and with respect to projected  local map tiles you may have a look at makeTile help.
cheers chris

**Comment by jcheng5** [comment] 2016-09-01 22:51
@bhaskarvk Would be great to investigate this in the v1.1 timeframe (still use proj4leaflet? or move to Leaflet 1.0? etc.) though not necessarily fix for this release.

**Comment by bhaskarvk** [comment] 2016-09-14 22:44
Some discussion here for ref. https://github.com/environmentalinformatics-marburg/mapview/issues/13.
The biggest issue is the CRS needs to be specified at Map creation which happens inside the Widget factory/initialize function, where there is no way to pass params.

This the current code. Passing a CRS to it is not going to be easy. Probably impossible.

```javascript
HTMLWidgets.widget({
  name: "leaflet",
  type: "output",
  initialize: function(el, width, height) {
    // hard-coding center/zoom here for a non-empty initial view, since there
    // is no way for htmlwidgets to pass initial params to initialize()
    let map = L.map(el, {
      center: [51.505, -0.09],
      zoom: 13
    });

```

**Comment by timelyportfolio** [comment] 2016-09-15 14:46
Probably a dumb question, but does the Map creation need to occur in `initialize`.  Leaflet is far more complicated than most of my simple `htmlwidgets`, but in general I prefer to defer creation until `render` when we have `x`.

**Comment by bhaskarvk** [comment] 2016-09-15 14:49
We are thinking along the same lines. I'll have to dig thru. HTMLWidget code to see how to do that.

**Comment by timelyportfolio** [comment] 2016-09-15 14:52
I would start by just copying/pasting all the `initialize` code to before `doRenderValue` in `render`.  Happy to submit pull if easier.

**Comment by bhaskarvk** [comment] 2016-09-15 14:53
Don't bother, I'm almost half way there. Trying to refactor it to new binding specs of htmlwidgets 0.6 too.

**Comment by timelyportfolio** [comment] 2016-09-15 14:54
great, 2-in-1 :)

**Comment by bhaskarvk** [comment] 2016-09-15 15:01
Ideally htmlwidget's factory's return object should support a 'initialize' callback, which gets called right after the JS deps are loaded, & before renderValue.

**Comment by bhaskarvk** [comment] 2016-09-15 15:15
Might not be as straight forward, there's the shiny part too.

**Comment by bhaskarvk** [comment] 2016-09-15 17:58
I think I've made progress on this front. Expect to see results in a day or two.

**Comment by bhaskarvk** [comment] 2016-09-15 22:22
Got it! http://rpubs.com/bhaskarvk/proj4leaflet
I still need to iron out the API, but we got by jove.

**Comment by gisma** [comment] 2016-09-15 22:44
Thanks great job! 
Way more comfortable and generic than the "clunky" wokraround in projView. Now real mapping and adequate spatial visualisation can start.

**Comment by bhaskarvk** [comment] 2016-09-16 13:03
OK there's a minor potential incompatibility here.
In earlier HTMLWidgets (pre 0.6) you returned the widget object which in our case happens to be the Map. so you could do 
```r
leaflet() %>% addTiles() %>%
htmlwidgets::onRender("
 new L.divIcon(....).addTo(this);
")
```

where the `this` was an instance of `L.map`.
Now in order to support passing options to the L.map constructor, I moved the map creation inside of the `render` code, but I also had to adapt to the newer binding specs of htmlwidgets 0.6
and here you return an object with contains your map instance along with `factory`, `renderValue` and `resize` functions.
http://www.htmlwidgets.org/develop_intro.html
So now in `onRender` you can't use this to refer to the `L.map` instance, rather you'll have to get your map using `this.map`.
This will mean every onRender implementation needs to change. This is not a API change perse as the R API is same. 

Thoughts/comments @jcheng5 / @timelyportfolio , others ?

**Comment by bhaskarvk** [comment] 2016-09-16 13:05
FWIW my inclination is to go ahead and introduce this change because the pros (control over map instance creation) out weigh the cons (potential rewrite of code inside onRender). 
onRender is a special use case anyways and in no way will affect majority of the user base. But I'm interested in opinion from long time users and core devs.

**Comment by bhaskarvk** [comment] 2016-09-16 13:23
This is an working example with my change

```r
leaflet(mapOptions = list(crs=list('_class'='L.CRS.Simple'))) %>%
  fitBounds(0,0,1000,1000) %>%
  # for now via
  htmlwidgets::onRender("
  function(el, t) {
    var myMap = this.getMap();
    var bounds = myMap.getBounds();
  	var image = new L.ImageOverlay(
                      'http://leafletjs.com/examples/crs-simple/uqm_map_full.png',
                      bounds);
    image.addTo(myMap);
  }
  ")
```

**Comment by timelyportfolio** [comment] 2016-09-16 15:20
I agree with you @bhaskarvk that benefits greatly outweigh the inconvenience.

**Comment by bhaskarvk** [comment] 2016-09-16 19:08
Here's the updated version now with demos for L.CRS.Simple and some other Projections.
http://rpubs.com/bhaskarvk/proj4leaflet

**Comment by jcheng5** [comment] 2016-09-17 12:02
Let's discuss our options. I really hate to break compatibility if there's a way to avoid it. It's drastic but we could modify htmlwidgets to let us decorate the call to the onRender callback, for example. The big downside is then having to release htmlwidgets to CRAN first.

**Comment by tim-salabim** [comment] 2016-09-18 12:28
I also agree with @bhaskarvk that the benefits are huge in comparison to the potential problem of breaking onRender calls. As from a mapview point of view we do have a couple of functions using `onRender` which we could quickly fix to accommodate changes. On the other hand, spatial analysis without visual support for special CRSs is pretty useless, so this is a must have for a package like mapview. Therefore, I'd happily fix some broken bit, if this means we can finally get proper redering of data with abitrary CRS. I think the vast majority of spatial analysts will agree with this.

**Comment by jhollist** [comment] 2016-09-18 13:16
Agree completely with @tim-salabim!  CRS support is huge!

**Comment by bhaskarvk** [comment] 2016-09-18 14:43
I've been thinking, the minor incompatibility is not due to CRS support per se. It's due to how htmlwidget's contract changed in 0.6.
So at any time we migrated Leaflet's code to htmlwidget 0.6 we will have to implement this change.
So better we do it now.
Also onRender is a very very specialized use case, so I think the people affected by this is very minimal, and besides the the actual R or javascript API is not changing, we're just changing (rather htmlwidgets 0.6 is changing) what the 'this' object refers to in the onRender function.

**Comment by jcheng5** [comment] 2016-09-18 17:47
Don't worry, I'm not suggesting not to implement the CRS support, just to look for a way to do so without breaking onRender code that's already out there. I just want the chance to try myself before giving up on the idea of doing it in a backwards compatible way.

**Comment by jcheng5** [comment] 2016-09-18 17:53
@bhaskarvk is there a branch I can look at yet? Even if it's half baked?

**Comment by bhaskarvk** [comment] 2016-09-18 19:01
Coming up. I had one up but it was not even quarter baked. I'll push out one for you to look at in an hour or so.

**Comment by bhaskarvk** [comment] 2016-09-18 20:01
Created PR #294

**Comment by bhaskarvk** [comment] 2016-09-26 18:03
Proj4Leaflet support merged in master.

**Closed by bhaskarvk** 2016-09-26 18:03 UTC
Labels: enhancement, in progress
