### ISSUE TITLE
Is zoom to feature possible with current package?

### ISSUE THREAD

**Issue by efh0888** [rstudio/leaflet#132] opened 2015-06-23 19:32 UTC
I'm making some good headway on a demo app that uses leaflet for a drill-down choropleth map, which has led me to this issue. See my post at https://github.com/rstudio/leaflet/issues/41...

Anyway, as part of that project, I'm wanting to incorporate the zoomToFeature functionality shown in the app https://www.mapbox.com/mapbox.js/example/v1.0.0/choropleth/. My guess is it's currently not possible as I don't see any function to take care of the getBounds() part. I think this would be super useful, especially when paired with the drill-down.

**Comment by jcheng5** [comment] 2015-06-23 22:17
It's possible to do if you're in Shiny, but you will need to find the bounds in R (which should be easy if your data is in, say, `sp` format--just use the `bbox()` function). For a non-Shiny map, you're right, there is no support for this at the moment, but it'd make a nice addition.

**Comment by efh0888** [comment] 2015-06-23 22:47
Sweet, that's good to know. So then in a Shiny app, it'd be something like

```
states <- SpatialPolygonsDataFrame(...)
box <- bbox(states)

leaflet(states) %>%
  addTiles() %>%
  fitBounds(lat1 = box[1], lng1 = box[2], lat2 = box[3], lng2 = box[4])
```

**Comment by jcheng5** [comment] 2015-06-23 23:31
Yes. I've sent you a pull request with a ton of changes, including this one.

I think there's a bug in fitBounds where, if you use it with a
leafletProxy, you can't have any chained methods come after it--it doesn't
return the leafletProxy on to the next link in the chain. I'll get this
fixed on GitHub but it didn't make the release I just sent to CRAN.

**Comment by pulsinger** [comment] 2016-03-15 15:40
Has this been solved / implemented in Leaflet 1.0.1 (which I'm currently using) ? 
At the moment fitBounds gives error when I use it with _leafletProxy()_ and _shinyApp_ obviously crashes. When using fitBounds with_ leaflet()_, it works. However, the map is being redrawn all over again...which is exactly what I was trying to avoid by using _leafletProxy()

**Comment by ideamotor** [comment] 2016-03-15 21:18
Works for me and map is not redrawn. Maybe you are thinking of the basemap tiles (which are likely new on a new zoom level) ? `setView` works if you don't want to change the zoom (or if you know what it should be).

**Comment by jcheng5** [comment] 2016-03-15 22:05
@pulsinger Can you post a minimal reproducible example of the crashing you're seeing?

**Comment by pulsinger** [comment] 2016-03-16 13:35
The warning is: "_Warning: Error in dispatch: Invalid map parameter_"
It works perfectly when using leaflet(), gives error when using the same _fitBounds_ with leafletproxy.
Below is a reproducible example (should work).

**Server.R:**

library(shiny)
library(leaflet)
library(raster)
library(rgeos)
library(rgdal)

server <- function(input, output, session) {
  
  ga <- reactive({
    getData('GADM', country = input$cnt , level=input$admin)
  })
 
 output$map <- renderLeaflet({
   gbox <- bbox(ga())
   
    leaflet() %>% 
      #fitBounds(lng1 = gbox[1],lat1 = gbox[2],lng2 = gbox[3],lat2 = gbox[4]) %>% # fit bounds to country
      addProviderTiles("CartoDB.Positron")  
  })  
  
  observe({
    
    gaf <- ga()         # observe won't work with reactive spatialdataframes ?
    gaf$area_10 <- gArea(gaf,byid=TRUE)   # calculate some spatial parameter
    gbox <- bbox(gaf)   # determine bounds from spatialdataframe
    
    pal <- colorNumeric("Greens", NULL,na.color = "#808080")   # create a color palette for polygons
    pol_pop <- paste0("<strong>Area: </strong>",gaf$area_10)   # create pop-up
    
    leafletProxy("map",session) %>%
      fitBounds(lng1 = gbox[1],lat1 = gbox[2],lng2 = gbox[3],lat2 = gbox[4])  %>%   
      addPolygons(data = gaf,weight=1,smoothFactor = 1,fillOpacity = 0.5,color="green",
                  fillColor = ~pal(area_10),popup = pol_pop)
  }) 
}

**Ui:**
library(shiny)
library(leaflet)
library(countrycode)
library(raster)

listcnt <- list()          
for (l in 1:(length(getData('ISO3')[,1]))) {
  name <- as.character(getData('ISO3')[,2])
  listcnt[name[l]] <- as.character(getData('ISO3')[l,1])
}

ui <- bootstrapPage(
  tags$style(type = "text/css", "html, body {width:100%;height:100%}"),
  leafletOutput("map", width = "100%", height = "100%"),
  absolutePanel(top = 10, right = 10,
                selectInput("cnt", "Choose country:",listcnt),
                sliderInput("admin", "Administration level:",min=0,max=3,step=1,value = 0,
                            ticks = FALSE)
  )
)

**Comment by ideamotor** [comment] 2016-03-16 18:18
@pulsinger this works and you are using leafletProxy. I'm not sure if you mean this, but you can't reference `leafletProxy("map")` within the `output$map <- renderLeaflet({...})` statement that initiates it.

**Comment by pulsinger** [comment] 2016-03-22 09:42
Thanks for the help, it was bad coding from my side.

**Closed** 2016-09-01 23:58 UTC
