### ISSUE TITLE
Leaflet Heatmap?

### ISSUE THREAD

**Issue by ignacio82** [rstudio/leaflet#137] opened 2015-06-26 12:08 UTC
Is [this](http://www.patrick-wied.at/static/heatmapjs/example-heatmap-leaflet.html) currently possible or in your road map?

Thanks!

**Comment by dkincaid** [comment] 2015-07-07 22:53
We would also be very interested in this.

**Comment by jcheng5** [comment] 2015-07-08 02:04
Not sure how to choose between that and this:
https://github.com/Leaflet/Leaflet.heat

Anyone have any thoughts?

**Comment by cholcomb** [comment] 2015-07-20 21:04
FWIW, Leaflet.heat is developed by the primary dev on Leaflet itself (the default gradient sucks but it's easy to change).

**Comment by timelyportfolio** [comment] 2015-08-26 13:47
I can take a shot at it if no one else is volunteering. Since `Leaflet.heat` is the official, I'll probably start with that.

**Comment by ramnathv** [comment] 2015-08-26 17:42
This should be fairly easy to implement. Here is a blog post I did long back on adding `Leaflet.heat` to `rMaps` http://rmaps.github.io/blog/posts/leaflet-heat-maps/index.html. The key steps here involve:

1. Adding a conditional dependency to `Leaflet.heat` assets.
2. Access the map object and add a heatLayer.
3. Pass data to this layer.

**Comment by jcheng5** [comment] 2015-08-26 18:12
@timelyportfolio Nobody has started on it--please feel free!

**Comment by bhaskarvk** [comment] 2016-10-11 12:37
Dupe of #223 

Added heatmap support in https://github.com/bhaskarvk/leaflet.extras which will soon be on CRAN.
Demo http://rpubs.com/bhaskarvk/leaflet-heatmap

**Closed by bhaskarvk** 2016-10-11 12:37 UTC
Labels: duplicate, enhancement
