### ISSUE TITLE
Update of map not works

### ISSUE THREAD

**Issue by yoelii** [rstudio/leaflet#892] opened 2023-11-24 16:07 UTC
Hi, 

I use leaflet package in a shiny app. I previously code a update of my map like is exemplained in tutoriel ( with leafletProxy )

Without changes in my code, the map is not updated when I selected other data (in my code, I select another year  like in this app https://esbriskin.shinyapps.io/Media_Freedoms/ , so typically another row in my matrix)

When I check in google chrome DevTools, I can see a js error : 

```r
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'calls')
    at e.<anonymous> (leaflet.js:829:77)
    at e.<anonymous> (shinyapp.ts:825:40)
    at v (shinyapp.ts:5:1357)
    at Generator.<anonymous> (shinyapp.ts:5:4174)
    at Generator.next (shinyapp.ts:5:2208)
    at F_ (shinyapp.ts:6:99)
    at u (shinyapp.ts:7:194)
    at shinyapp.ts:7:364
    at new Promise (<anonymous>)
    at e.<anonymous> (shinyapp.ts:7:97)
```

```js
if (!map.leafletr.hasRendered) {
      map.leafletr.pendingRenderData.calls = map.leafletr.pendingRenderData.calls.concat(data.calls);
      return;
    }
```

My Code : 

```r
server.R 


# renderLeaflet map 1
    output$map_1 <- renderLeaflet({
        my_output()
        my_data_map <- make_data_for_map(data1 = data_countries_amr, data2 = parameters_ui_amr$output_1_country_1, year = 1)
        map <- joinCountryData2Map(my_data_map, joinCode = "ISO3",
                            nameJoinColumn = "ISO")
        pal <- colorBin("YlOrRd", domain = my_data_map$col_i*10000, bins = 5, pretty = TRUE)
        map_leaflet <- leaflet(map) %>%
                        addTiles() %>%
                        setView(0,0,2) %>%
                        addPolygons(fillColor = ~pal(map$col_i*10000),
                                    weight = 2,
                                    opacity = 1,
                                    color = "white",
                                    dashArray = "3",
                                    fillOpacity = 0.7,
                                    # stroke = FALSE, smoothFactor = 0.3,
                                    highlight = highlightOptions(
                                    weight = 5,
                                    color = "white",
                                    dashArray = "3",
                                    fillOpacity = .8,
                                    bringToFront = TRUE),
                                    label = ~paste0( map$Country, ": ",map$col_i))%>%
                        addLegend(pal = pal, values = ~col_i, opacity = 1) %>%
                        addEasyButton(easyButton(
                            icon = "fa-globe", title = "Zoom to Level 1",
                            onClick = JS("function(btn, map){ map.setZoom(1); }"))) %>%
                        addMiniMap()
    })


 # Incremental changes to the map with knobInput
    observeEvent(input$year_selected, {

        if (length(parameters_ui_amr$output_1_country_1) >= 1){
        my_data_map <- make_data_for_map(data1 = data_countries_amr, data2 = parameters_ui_amr$output_1_country_1, year = as.numeric(input$year_selected))
        map <- joinCountryData2Map(my_data_map, joinCode = "ISO3",
                            nameJoinColumn = "ISO")
        pal <- colorBin("YlOrRd", domain = my_data_map$col_i*10000, bins = 5, pretty = TRUE)
        map_leaflet <- leafletProxy("map_1", data = map) %>%
                        addTiles() %>%
                        setView(0,0,2) %>%
                        addPolygons(fillColor = ~pal(map$col_i*10000),
                                    weight = 2,
                                    opacity = 1,
                                    color = "white",
                                    dashArray = "3",
                                    fillOpacity = 0.7,
                                    # stroke = FALSE, smoothFactor = 0.3,
                                    highlight = highlightOptions(
                                    weight = 5,
                                    color = "white",
                                    dashArray = "3",
                                    fillOpacity = .8,
                                    bringToFront = TRUE),
                                    label = ~paste0( map$Country, ": ",map$col_i))
        map_leaflet %>% clearControls() # Delete the previous legend
        map_leaflet <- map_leaflet %>% addLegend(pal = pal, values = ~col_i, opacity = 1)

        }
        # Update also SliderTextInput
        updateSliderTextInput(session = session, inputId = "year_two" , selected = input$year_selected )

    })

    # Incremental changes to the map with SliderTextInput
    observeEvent(input$year_two, {

        if (length(parameters_ui_amr$output_1_country_1) >= 1){
            my_data_map <- make_data_for_map(data1 = data_countries_amr, data2 = parameters_ui_amr$output_1_country_1, year = as.numeric(input$year_two))
            map <- joinCountryData2Map(my_data_map, joinCode = "ISO3",
                                nameJoinColumn = "ISO")
            pal <- colorBin("YlOrRd", domain = my_data_map$col_i*10000, bins = 5, pretty = TRUE)
            map_leaflet <- leafletProxy("map_1", data = map) %>%
                            addTiles() %>%
                            setView(0,0,2) %>%

                            addPolygons(fillColor = ~pal(map$col_i*10000),
                                        weight = 2,
                                        opacity = 1,
                                        color = "white",
                                        dashArray = "3",
                                        fillOpacity = 0.7,
                                        # stroke = FALSE, smoothFactor = 0.3,
                                        highlight = highlightOptions(
                                        weight = 5,
                                        color = "white",
                                        dashArray = "3",
                                        fillOpacity = .8,
                                        bringToFront = TRUE),
                                        label = ~paste0( map$Country, ": ",map$col_i))
            map_leaflet %>% clearControls() # Delete the previous legend
            map_leaflet <- map_leaflet %>% addLegend(pal = pal, values = ~col_i, opacity = 1)
        }
        # Update also KnobInput
        updateKnobInput(session = session, inputId = "year_selected", value = input$year_two )

    })


#renderUI "output1" --> part to display output 1
    output$output_1_part <- renderUI(

        tags$div(class = "output",
        tags$div(
            tags$div(class = "subtitle",
            p(class = "text",
                HTML("<b class ='output_title'>OUTPUT 1 </b>")
            )
            ),
            tags$div(class = "text",
            p(class = "text_output", "AMR simulation compute for : ", parameters_ui$country_1),
            p(class = "text_output", "Bacteria : ", parameters_ui$bacteria),
            p(class = "text_output", "beta : ", parameters_ui_amr$beta_tuned),
            p(class = "text_output", "sigma S : ", parameters_ui_amr$sigma_S_tuned),
            p(class = "text_output",random_text(nwords = 150))

            ),
            br(),
            tags$div(class = "subtitle",
            p(class = "output_subtitle", parameters_ui$country_1
                # HTML("<b class ='output_subtitle'>Test: ",,"</b>")
            )
            ),
            tags$div(class = "map",
               leafletOutput("map_1", height = 900), 
                absolutePanel(top = "85%", right = "75%", height = 100, width =  100, fixed = FALSE,
                    knobInput(
                    inputId = "year_selected",
                    label = "",
                    value = 1,
                    min = 0,
                    max = 20,
                    displayPrevious = FALSE, 
                    lineCap = "round",
                    # fgColor = "#F37C05",
                    fgColor = "#F88716",
                    bgColor = "FFFFFF",
                    inputColor = "#F88716",
                    width = 100,
                    height = 100,
                    immediate = FALSE
                    )
                ),
                sliderTextInput(
                    inputId = "year_two",
                    label = "Year after emergence :",
                    choices = c(1, 2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20),
                    grid = TRUE,
                    selected = 1,
                    width = "95%"
                )
            ), # end div map
            br()
        )
        ) # end div output 1
    ) # end renderUI output_1_part

```

```
sessionInfo() 

sessionInfo()
R version 4.3.1 (2023-06-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.3 LTS

Matrix products: default
BLAS:   /usr/local/lib/R/lib/libRblas.so 
LAPACK: /usr/local/lib/R/lib/libRlapack.so;  LAPACK version 3.11.0

locale:
 [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8    
 [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8   
 [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

time zone: Etc/UTC
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] shinycssloaders_1.0.0 rworldmap_1.3-8       sp_2.1-1             
 [4] leaflet_2.2.1         slickR_0.6.0          htmlwidgets_1.6.3    
 [7] shinipsum_0.1.0       shiny.router_0.3.1    shinyjs_2.1.0        
[10] shinyWidgets_0.8.0    shiny_1.7.5.1        

loaded via a namespace (and not attached):
 [1] plotly_4.10.3     sass_0.4.7        utf8_1.2.4        generics_0.1.3   
 [5] tidyr_1.3.0       xml2_1.3.5        lattice_0.21-8    digest_0.6.33    
 [9] magrittr_2.0.3    attempt_0.3.1     grid_4.3.1        maps_3.4.1.1     
[13] fastmap_1.1.1     jsonlite_1.8.7    promises_1.2.1    httr_1.4.7       
[17] spam_2.10-0       purrr_1.0.2       fansi_1.0.5       crosstalk_1.2.0  
[21] viridisLite_0.4.2 scales_1.2.1      dygraphs_1.1.1.6  codetools_0.2-19 
[25] lazyeval_0.2.2    jquerylib_0.1.4   cli_3.6.1         rlang_1.1.2      
[29] ellipsis_0.3.2    munsell_0.5.0     base64enc_0.1-3   cachem_1.0.8     
[33] raster_3.6-26     tools_4.3.1       dplyr_1.1.4       colorspace_2.1-0 
[37] ggplot2_3.4.4     httpuv_1.6.12     DT_0.30           vctrs_0.6.4      
[41] R6_2.5.1          mime_0.12         zoo_1.8-12        lifecycle_1.0.4  
[45] pkgconfig_2.0.3   terra_1.7-55      bslib_0.5.1       pillar_1.9.0     
[49] later_1.3.1       gtable_0.3.4      glue_1.6.2        data.table_1.14.8
[53] Rcpp_1.0.11       fields_15.2       tibble_3.2.1      tidyselect_1.2.0 
[57] xtable_1.8-4      htmltools_0.5.7   dotCall64_1.1-0   compiler_4.3.1
```
My Code works fine in this configuration : 

```
sessionInfo()
R version 4.3.1 (2023-06-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.3 LTS

Matrix products: default
BLAS:   /usr/local/lib/R/lib/libRblas.so 
LAPACK: /usr/local/lib/R/lib/libRlapack.so;  LAPACK version 3.11.0

locale:
 [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8    
 [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8   
 [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

time zone: Etc/UTC
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] shinycssloaders_1.0.0 rworldmap_1.3-8       sp_2.1-1             
 [4] leaflet_2.2.0         slickR_0.6.0          htmlwidgets_1.6.2    
 [7] shinipsum_0.1.0       shiny.router_0.3.1    shinyjs_2.1.0        
[10] shinyWidgets_0.8.0    shiny_1.7.5.1        

loaded via a namespace (and not attached):
 [1] plotly_4.10.3     sass_0.4.7        utf8_1.2.4        generics_0.1.3   
 [5] tidyr_1.3.0       xml2_1.3.5        lattice_0.21-8    digest_0.6.33    
 [9] magrittr_2.0.3    attempt_0.3.1     grid_4.3.1        maps_3.4.1.1     
[13] fastmap_1.1.1     jsonlite_1.8.7    promises_1.2.1    httr_1.4.7       
[17] spam_2.10-0       purrr_1.0.2       fansi_1.0.5       crosstalk_1.2.0  
[21] viridisLite_0.4.2 scales_1.2.1      dygraphs_1.1.1.6  codetools_0.2-19 
[25] lazyeval_0.2.2    jquerylib_0.1.4   cli_3.6.1         rlang_1.1.2      
[29] ellipsis_0.3.2    munsell_0.5.0     base64enc_0.1-3   cachem_1.0.8     
[33] raster_3.6-26     tools_4.3.1       dplyr_1.1.3       colorspace_2.1-0 
[37] ggplot2_3.4.4     httpuv_1.6.12     DT_0.30           vctrs_0.6.4      
[41] R6_2.5.1          mime_0.12         zoo_1.8-12        lifecycle_1.0.4  
[45] pkgconfig_2.0.3   terra_1.7-55      bslib_0.5.1       pillar_1.9.0     
[49] later_1.3.1       gtable_0.3.4      glue_1.6.2        data.table_1.14.8
[53] Rcpp_1.0.11       fields_15.2       tibble_3.2.1      tidyselect_1.2.0 
[57] xtable_1.8-4      htmltools_0.5.7   dotCall64_1.1-0   compiler_4.3.1  

```

Do you have a idea why the update not works ? htmlwidgets version ? 
Thanks you for your help

**Comment by gadenbuie** [comment] 2023-11-25 03:20
Thanks for the report. You're right, the latest version of htmlwidgets is the culprit. If you can use htmlwidgets 1.6.2 for the time being, that should resolve your problem until we work out how to fix this at a larger level.

I'm going to close this issue, since it's a duplicate of #891.

**Closed by gadenbuie** 2023-11-25 03:20 UTC
