### ISSUE TITLE
Leaflet maps don't appear in RStudio Viewer Pane (Windows + R 4.4

### ISSUE THREAD

**Issue by caballeroarturo** [rstudio/leaflet#919] opened 2024-05-17 18:56 UTC
After I upgraded to R studio, leaflet stopped working correctly.

library(leaflet)

m <- leaflet() %>%
  addTiles() %>% 
  addMarkers(lng=174.768, lat=-36.852, popup="Hola")
m 

> sessionInfo()
R version 4.4.0 (2024-04-24 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=Spanish_Mexico.utf8  LC_CTYPE=Spanish_Mexico.utf8    LC_MONETARY=Spanish_Mexico.utf8
[4] LC_NUMERIC=C                    LC_TIME=Spanish_Mexico.utf8    

time zone: America/Mexico_City
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] leaflet.extras_1.0.0 leaflet_2.2.2        sf_1.0-16            dplyr_1.1.4          highcharter_0.9.4   
[6] ggplot2_3.5.1        lubridate_1.9.3     

loaded via a namespace (and not attached):
 [1] plotly_4.10.4           utf8_1.2.4              generics_0.1.3          tidyr_1.3.1            
 [5] class_7.3-22            KernSmooth_2.23-22      stringi_1.8.4           lattice_0.22-6         
 [9] digest_0.6.35           magrittr_2.0.3          grid_4.4.0              timechange_0.3.0       
[13] fastmap_1.1.1           jsonlite_1.8.8          e1071_1.7-14            backports_1.4.1        
[17] DBI_1.2.2               httr_1.4.7              purrr_1.0.2             fansi_1.0.6            
[21] crosstalk_1.2.1         viridisLite_0.4.2       scales_1.3.0            jquerylib_0.1.4        
[25] lazyeval_0.2.2          rlist_0.4.6.2           cli_3.6.2               rlang_1.1.3            
[29] units_0.8-5             munsell_0.5.1           yaml_2.3.8              withr_3.0.0            
[33] tools_4.4.0             colorspace_2.1-0        pacman_0.5.1            broom_1.0.6            
[37] curl_5.2.1              assertthat_0.2.1        vctrs_0.6.5             R6_2.5.1               
[41] proxy_0.4-27            classInt_0.4-10         zoo_1.8-12              lifecycle_1.0.4        
[45] stringr_1.5.1           leaflet.providers_2.0.0 htmlwidgets_1.6.4       pkgconfig_2.0.3        
[49] pillar_1.9.0            gtable_0.3.5            Rcpp_1.0.12             data.table_1.15.4      
[53] glue_1.7.0              quantmod_0.4.26         tibble_3.2.1            tidyselect_1.2.1       
[57] rstudioapi_0.16.0       farver_2.1.2            htmltools_0.5.8.1       igraph_2.0.3           
[61] xts_0.13.2              compiler_4.4.0          TTR_0.24.4

**Comment by gadenbuie** [comment] 2024-05-17 19:44
Duplicate of #918

**Closed by gadenbuie** 2024-05-17 19:44 UTC
